services:
  migrate:
    build:
      context: .
      target: deps # use the deps stage — has node_modules + prisma
    command: npx prisma migrate deploy
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - default # same network as postgres

  app:
    build: .
    container_name: tst
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - migrate # app starts only after migrations run
    networks:
      - default

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 512m
    networks:
      - default

networks:
  default:

volumes:
  postgres_data:
