import { writeFile } from "node:fs/promises";

import { buildProductDeliveryIndexes } from "@/data/regions/product-delivery-index";
import type { RegionSupplyData } from "@/data/regions/types";

export async function writeProductDeliveriesGenerated(
  regions: Record<string, RegionSupplyData>,
  outputPath: string,
) {
  const { locations, records } = buildProductDeliveryIndexes(regions);

  const source = `// Generated by scripts/generate-regions.ts.
// Do not edit by hand.
import type {
  ProductDeliveryLocation,
  ProductDeliveryRecord,
  ProductId,
} from "./types";

export const productDeliveryRecords = ${JSON.stringify(records, null, 2)} satisfies Partial<
  Record<ProductId, ProductDeliveryRecord[]>
>;

export const productDeliveries = ${JSON.stringify(locations, null, 2)} satisfies Partial<
  Record<ProductId, ProductDeliveryLocation[]>
>;

export function getProductDeliveryRecords(
  productId: ProductId,
): readonly ProductDeliveryRecord[] {
  const index: Partial<Record<ProductId, ProductDeliveryRecord[]>> =
    productDeliveryRecords;

  return index[productId] ?? [];
}

export function getProductDeliveryLocations(
  productId: ProductId,
): readonly ProductDeliveryLocation[] {
  const index: Partial<Record<ProductId, ProductDeliveryLocation[]>> =
    productDeliveries;

  return index[productId] ?? [];
}
`;

  await writeFile(outputPath, source, "utf8");

  return {
    productCount: Object.keys(locations).length,
    productLocationCount: Object.values(locations).reduce(
      (sum, productLocations) => sum + productLocations.length,
      0,
    ),
    productRecordCount: Object.values(records).reduce(
      (sum, productRecords) => sum + productRecords.length,
      0,
    ),
  };
}
